### ISSUE TITLE
Whitelisting Plugins

### ISSUE THREAD

**Issue by seanshahkarami** [waggle-sensor/plugin_manager#4]
In David's node, the `envsense` and `alphasense` plugins were not whitelisted and thus did not start once he'd connected the node.

Is this the expected default configuration or should this be changed? If we want to leave it as is, how do we decide on when to start a plugin once it's in the field. If we should change it, what if a device isn't connected?

**Comment by geeklair** [comment]
Two issues to tackle:

* The presence of external sensor plugins (chem, air, alpha, env, etc) (whitelist or not) should not impact the registration of the node, the ssh framework, reverse tunnels, and even pushing node-controller data to the beehive.  Even with no plugins the node should operate and report in correctly, and there should be a core data stream from the Node Controller to the beehive reporting on node status.

* WRT to whitelisting… Why wouldn’t we want every sensor that is attached and detected to activate a plugin automatically?  Put another way, If I plug in an AlphaSense into a node and reboot it, why should I have to connect via the console and whitelist something?

**Comment by seanshahkarami** [comment]
For the first part, my understanding now is that David's node just ended up in a weird state on Beehive, which he and Bill corrected manually. It sounds like it didn't have much, if anything, to do with those other services.

For the whitelisting point, Wolfgang and I talked about the autodetection idea some. It's not that we can't do it that way...it's just the way the plugin manager was designed as of now, so we'd have to add a thing to do that.

**Comment by gemblerz** [comment]
For now, system_base plugin (in branch-baseplugin) does 1) report system info to beehive, 2) auto-detect attached sensor boards and start the corresponding plugins, but not put the plugins in whitelist, and 3) report Wagman status every 30 seconds (we can discuss the reporting period, but it is just now 30 seconds).

To recap, after we merge the branch onto master, the question will be answered.

**Comment by MuffinSpawn** [comment]
The nodecontroller code has been merged, so this issue should be resolved. Closing...
